name: Upload To Web Store

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-24.04

    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.18.2

      - name: Setup npm
        run: npm install -g npm@10.9.2

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          EXTENSION_VERSION: ${{ github.event.release.tag_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build.zip
          path: build.zip
          retention-days: 1

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload'
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'build.zip'
